# Site Settings
title: Merry-Go-Round
email: lilliw2@gmail.com
description: >
  A Jekyll landing page with a carousel.
baseurl: ""
url: "http://localhost:4000"
twitter_username: 
github_username:  lillworkspace
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM